config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'courses#index'
  get 'courses/new', to: 'courses#new'
  get 'about', to: 'pages#about'
  resources :students, except: [:destroy]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'course_enroll', to: 'student_courses#create'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, presence: true, length: { minimum: 6, maximum: 50 }
  validates :short_name, presence: true, length: { minimum: 3, maximum: 15 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  
  has_many :student_courses
  has_many :students, through: :student_courses
  
end

app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase  }
  validates :name, presence: true, length: { minimum: 6, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i  
    validates :email, presence: true, length: { maximum: 105 },            
                         uniqueness: { case_sensitive: false },            
                           format: { with: VALID_EMAIL_REGEX }
                           
  has_secure_password
  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  
  belongs_to :student
  belongs_to :course
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= Student.find(session[:student_id]) if session[:student_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:notice] = "Please log in!"
      redirect_to login_path
    end
  end
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  #skip_before_action :require_user
  
  
  def index
    @courses = Course.all
  end
  
  def new
    
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #skip_before_action :require_user
  
  def about
    
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #skip_before_action :require_user, only: [:new, :create]
  
  def new
    
  end
  
  def create
    student = Student.find_by(email: params[:sessions][:email].downcase)
    if student && student.authenticate(params[:sessions][:password])
      session[:student_id] = student.id
      redirect_to student
    else
      flash.now[:notice] = "Incorrect Email/Password"
      render 'new'
    end
  end
  
  def destroy
    session[:student_id] = nil
    redirect_to root_path
  end
  
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController
  
  def create
    add_course = Course.find(params[:course_id])
    unless current_user.courses.include?(add_course)
    StudentCourse.create(course: add_course, student: current_user)
    flash[:notice] = "You hvae successfully enrolled in #{add_course.name}"
    redirect_to current_user
    else
      flash[:notice] = "Please try enrollment again"
      redirect_to root_path
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  #skip_before_action :require_user, only: [:new, :create]
  before_action :set_student, only: [:show, :edit, :update]
  before_action :require_same_student, only: [:edit, :update]
  
  def index
    @students = Student.all
  end
  
  def show
    
  end
  
  def new
    @student = Student.new
  end
  
  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:notice] = "Thank you for enrolling!"
      redirect_to @student
    else
      render 'new'
    end
  end
  
  def edit
    
  end
  
  def update
    if @student.update(student_params)
      redirect_to @student
    else
      render 'edit'
    end
    
  end
  
  def destroy
    
  end
  
  private
  
  def student_params
    params.require(:student).permit(:name, :email, :password, :password_confirmation)
  end
  
  
  def set_student
    @student = Student.find(params[:id])
  end
  
  def require_same_student
    if current_user != @student
      redirect_to student_path(current_user)
      flash[:notice] = "Profile Restricted"
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def session_link
    if (logged_in?)
      link_to "LOG OUT", logout_path, method: :delete
    else
      link_to "LOG IN", login_path
    end
  end
  
end

app/views/courses/index.html.erb
<div class="row">
  <div class="container"> 
  <div class="col s12">
    <h3 class="center-align">Course Listing</h3>
  </div>


<div class="row">
  <% @courses.each do |c| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title"><%= c.short_name %>: <%= c.name %></span>
            <p><%= c.description %></p>
          </div>
          <div class="card-action">
            <% if logged_in? && !(current_user.courses.include?(c)) %>
              <%= link_to "Enroll", course_enroll_path(course_id: c.id), method: :post %>
            <% end %>
            <a href="#">Info</a>
          </div>
        </div>
    </div>
  <% end %>

    

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Embassy Tech</h5>
        <p class="grey-text text-lighten-4">Start your IT Careeer Now. We will teach you how!</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Information</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Contact Us</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2014 Copyright Powered by Tristan Global
    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/layouts/_navigations.html.erb
<header> 
  <ul id="dropdown1" class="dropdown-content">
    <li><%= session_link %></li>
    <% if logged_in? %>
    <li><%= link_to "Profile", student_path(current_user) %></li>
    <% end %>
    <li class="divider"></li>
    <li><a href="#!">three</a></li>
  </ul>
  <ul id="dropdown2" class="dropdown-content">
    <li><%= session_link %></li>
    <% if logged_in? %>
    <li><%= link_to "Profile", student_path(current_user) %></li>
    <% end %>
    <li class="divider"></li>
    <li><a href="#!">three</a></li>
  </ul>
  <nav>
    <div class="nav-wrapper">
      <div class="container"> 
      <%= link_to "Embassy Tech", root_path, class: "brand-logo left" %>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to "Courses", root_path %></li>
      <% if (logged_in?) %>
        <li><%= link_to "Students", students_path %></li>
      <% end %>
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
      </ul>
      </div>
    </div>
  
    <ul class="sidenav" id="mobile-demo">
      <li><%= link_to "Courses", root_path %></li>
      <% if (logged_in?) %>
      <li><%= link_to "Students", students_path %></li>
      <% end %>
      <li><a href="badges.html">Enrollment</a></li>
      <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
  </nav>
  
  <% flash.each do |key, message| %>
    <div class="container">
      <div class="row enroll">
        <div class="col s12 m12 l12">
          <div class="card-panel red lighten-2" id="fade-out">
            <span class="white-text">
              <%= message %>
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  
  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Embassy Tech</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'layouts/navigations' %>
    <main> 
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="container">
    <div class="row enroll">
      <div class="col s12 m12 l12">
        <div class="card-panel red lighten-2">
          <span class="white-text">
          Please fix 
          <%= pluralize(obj.errors.count, "error") %>
            <ul>
              <strong><% obj.errors.full_messages.each do |msg| %></strong>
                <li>
                  <%= msg %>
                  
                </li>
              <% end %>
            </ul>
            <% end %>
          </span>  
        </div>
      </div>
    </div>
  </div>

app/views/students/_form.html.erb
<%= render 'shared/errors', obj: @student %>

<div class="container">
  <div class="row center enroll">
    <div class="col s12 m12 l12">
      <div class="card-panel">
      <h3 class="header">Enroll Now!</h3>
        <div class="row">
        <%= form_for(@student, html: { class: "col s12" }) do |f| %>
          <div class="row">
            <div class="input-field">
              <i class="material-icons prefix">account_circle</i>
              <%= f.text_field :name %>
              <%= f.label :name, placeholder: "Enter Name", class: "active" %>
            </div>
          </div>
          
          <div class="row">
            <div class="input-field">
              <i class="material-icons prefix">email</i>  
              <%= f.label :email %>
              <%= f.email_field :email, class: "active" %>
            </div>
          </div>
          
                    <div class="row">
            <div class="input-field">
              <i class="material-icons prefix">lock</i>  
              <%= f.label :password, class: "active" %>
              <%= f.password_field :password, placeholder: "Enter Password" %>
            </div>
          </div>
          
          <div class="row">
            <div class="input-field">
              <i class="material-icons prefix">lock</i>  
              <%= f.label :password_confirmation, class: "active" %>
              <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
            </div>
          </div>
          
          
          <div class="row">
            <div class="input-field">
              
              <%= f.button(@student.new_record? ? '<i class="material-icons right">arrow_forward</i>Enroll Now!'.html_safe : '<i class="material-icons right">arrow_forward</i>Update Profile'.html_safe, class: "waves-effect waves-light btn right" ) %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="row">
  <div class="container"> 
  <div class="col s12">
    <h3 class="center-align">Students Directory</h3>
  </div>


<div class="row">
  <% @students.each do |s| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title">Name: <%= s.name %></span>
            <p>Email: <%= s.email %></p>
            <p>Course Enrollments: None</p>
          </div>
          <div class="card-action">
            <%= link_to "View Profile", student_path(s) %>
          </div>
        </div>
    </div>
  <% end %>
    </div>
  </div>
</div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div class="row center enroll">
  <div class="container"> 
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title"><%= @student.name %></span>
            <p>Email: <%= @student.email %></p>
            <p>Course Enrollments: 
            <% if @student.courses.empty? %>
            None
            <% else %>
            <ul>
              <% @student.courses.each do |c| %>
                <li><%= c.name %></li>
              <% end %>
            </ul>
            <% end %>
            </p>
          </div>
          <div class="card-action">
            <a href="#">Current Enrollments</a>
            
          </div>
        </div>
        <% if current_user == @student %>
        <%= link_to '<i class="material-icons right">create</i>Edit Profile'.html_safe, edit_student_path(@student), class: "waves-effect waves-light btn" %>
        <% end %>
    </div>
  </div>
</div>